In [6]:
# 自行編排版面、排版、加上學號姓名

### Numpy 
##### 可使用在矩陣運算、線性代數、矩陣乘法、轉置、數學運算、統計運算...等
[連結](https://docs.scipy.org/doc/numpy/reference/routines.html)

In [54]:
# Array 之中的每一個元素都必須是相同型態

In [55]:
import numpy as np #使用numpy 採用np簡寫

array1 = np.array([1, 2, 3])  #一維的array
array2 = np.array([[1, 2, 3], [4, 5, 6]])  #二維的array

print(array2)
print('維度:',array2.ndim)    # 維度 ndim
print('行列:',array2.shape)   # 行列 shape
print('個數:',array2.size)    # 個數 size

[[1 2 3]
 [4 5 6]]
維度: 2
行列: (2, 3)
個數: 6


In [56]:
#一維陣列的運算
import numpy as np

a = np.array([3,6,9,12,15,18])
b = np.arange(6) # 0-5
c = np.zeros(6) # 數據全為0，6個
d = np.ones(6, dtype = np.int) # 數據為1，6個，整數
e = np.random.random(6) # 0-1浮點數，6個
f = b-a

print(a,b,c,d,e,f, sep="\n")
print(f < -9)
print(f == -9)

[ 3  6  9 12 15 18]
[0 1 2 3 4 5]
[ 0.  0.  0.  0.  0.  0.]
[1 1 1 1 1 1]
[ 0.39034556  0.4895589   0.1630484   0.04894905  0.24380781  0.13514918]
[ -3  -5  -7  -9 -11 -13]
[False False False False  True  True]
[False False False  True False False]


In [57]:
#多維陣列的運算
import numpy as np

a = np.array([[3,6,9],[12,15,18]])
b = np.arange(6).reshape(2,3) # 一維轉成2X3
c = np.zeros((2,3)) # 數據全為0
d = np.ones((2,3), dtype = np.int) # 數據為1，6個
e = np.random.random((2,3)) #亂數，6個

print(a,b,c,d,e, sep="\n")
print(np.sum(a))
print(np.sum(a, axis=0)) # 欄位(直)的加總
print(np.sum(a, axis=1)) # 欄位(橫)的加總

[[ 3  6  9]
 [12 15 18]]
[[0 1 2]
 [3 4 5]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
[[ 0.54118256  0.11942453  0.42653161]
 [ 0.23741923  0.26968139  0.88765807]]
63
[15 21 27]
[18 45]


In [58]:
#加減乘除法 (*非矩陣乘法*)
import numpy as np
A=np.array([[2,4,6],[8,10,12]])
B=np.arange(6).reshape((2,3)) 

print(A)
print(B)

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]


In [59]:
# AB的加減乘除法
A*B

array([[ 0,  4, 12],
       [24, 40, 60]])

In [60]:
# 矩陣乘法
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(6).reshape((2,3)) 

print(a)
print(b)
print(b.T) # transpose


[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [61]:
# 矩陣乘法 dot
print(np.dot(a,b.T))

[[ 16  52]
 [ 34 124]]


In [62]:
# array 合併
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B))) #vertical
print(np.hstack((A,B))) #horizontal


[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [63]:
# array 分割
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #vertical
print(np.hsplit(a,2)) #horizontal

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### Pandas
##### Pandas建構於Numpy上，Python做資料分析常⽤的套件
- Numpy 是array形式的，沒有欄位名稱或標籤
- Pandas 基於Numpy構建的，有列表的標籤。


##### Series

In [64]:
# Series是有index的一維array
import pandas as pd
import numpy as np
# 建立一個 Series 有整數、字串、NAN、浮點數、布林
s = pd.Series([1, "abc", np.nan, 3.14, True])

print(s)
#如果是numpy的array呢?

0       1
1     abc
2     NaN
3    3.14
4    True
dtype: object


##### DataFrame

In [65]:
# 生成方式一：用array的矩陣(1)
df = pd.DataFrame(np.random.randn(7,3))
print(df)

          0         1         2
0 -0.550891  1.662062  1.059183
1  0.110977  0.349744 -0.047115
2  0.313159  1.248155 -0.001265
3 -0.501820 -0.099204  0.629400
4 -0.627391 -0.442786  0.594354
5 -0.686602  1.197554  0.115349
6  1.291151  0.528914 -0.212295


In [66]:
df

0         1         2
0 -0.550891  1.662062  1.059183
1  0.110977  0.349744 -0.047115
2  0.313159  1.248155 -0.001265
3 -0.501820 -0.099204  0.629400
4 -0.627391 -0.442786  0.594354
5 -0.686602  1.197554  0.115349
6  1.291151  0.528914 -0.212295

In [67]:
# 生成方式一：用array的矩陣(2)
eat = np.random.randint(10,size=(7,3))*5+50
dates = pd.date_range('20171028',periods=7)
df0 = pd.DataFrame(eat)
#加上欄位
df1 = pd.DataFrame(eat, index=dates, columns=['早餐','午餐','晚餐'])
print(df1)

            早餐  午餐  晚餐
2017-10-28  85  70  65
2017-10-29  90  65  70
2017-10-30  50  60  90
2017-10-31  85  65  85
2017-11-01  65  80  95
2017-11-02  90  70  85
2017-11-03  95  75  55


In [68]:
df1

早餐  午餐  晚餐
2017-10-28  85  70  65
2017-10-29  90  65  70
2017-10-30  50  60  90
2017-10-31  85  65  85
2017-11-01  65  80  95
2017-11-02  90  70  85
2017-11-03  95  75  55

In [69]:
eat = np.random.randint(10,size=(7,3))*5+50
print(eat)

[[65 65 70]
 [90 90 95]
 [70 80 80]
 [60 65 85]
 [70 70 50]
 [50 60 75]
 [80 75 75]]


In [70]:
#生成方式二，字典方式
df2 = pd.DataFrame({'小數' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    '整數' : np.array([3] * 4,dtype='int32'),
                    '時間' : pd.Timestamp('20170812'),
                    '類別資料' : pd.Categorical(["test","train","test","train"]),                     
                   }) 
#字典的key代表甚麼? colums name
#dtype指定資料格式? Y
print(df2)

    小數  整數         時間   類別資料
0  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
2  1.0   3 2017-08-12   test
3  1.0   3 2017-08-12  train


In [71]:
df2

小數  整數         時間   類別資料
0  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
2  1.0   3 2017-08-12   test
3  1.0   3 2017-08-12  train

In [72]:
#DataFrame的屬性
print(df2)
print(df2.dtypes)
print(df2.index) #print(df2.columns), print(df2.values)
print(df2.describe()) #有甚麼要注意的呢?

print(df2.T)
print(df2.sort_index(axis=1, ascending=False))
print(df2.sort_values(by='類別資料'))


    小數  整數         時間   類別資料
0  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
2  1.0   3 2017-08-12   test
3  1.0   3 2017-08-12  train
小數             float32
整數               int32
時間      datetime64[ns]
類別資料          category
dtype: object
Int64Index([0, 1, 2, 3], dtype='int64')
        小數   整數
count  4.0  4.0
mean   1.0  3.0
std    0.0  0.0
min    1.0  3.0
25%    1.0  3.0
50%    1.0  3.0
75%    1.0  3.0
max    1.0  3.0
                        0                    1                    2  \
小數                      1                    1                    1   
整數                      3                    3                    3   
時間    2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料                 test                train                 test   

                        3  
小數                      1  
整數                      3  
時間    2017-08-12 00:00:00  
類別資料                train  
    類別資料         時間  整數   小數
0   test 2017-08-12   3  1.0
1  train 20

In [73]:
df2

小數  整數         時間   類別資料
0  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
2  1.0   3 2017-08-12   test
3  1.0   3 2017-08-12  train

In [74]:
print(df2.dtypes)

小數             float32
整數               int32
時間      datetime64[ns]
類別資料          category
dtype: object


In [75]:
print(df2.index) #print(df2.columns), print(df2.values)

Int64Index([0, 1, 2, 3], dtype='int64')


In [76]:
print(df2.describe()) #有甚麼要注意的呢?

        小數   整數
count  4.0  4.0
mean   1.0  3.0
std    0.0  0.0
min    1.0  3.0
25%    1.0  3.0
50%    1.0  3.0
75%    1.0  3.0
max    1.0  3.0


In [77]:
df2.T

0                    1                    2  \
小數                      1                    1                    1   
整數                      3                    3                    3   
時間    2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料                 test                train                 test   

                        3  
小數                      1  
整數                      3  
時間    2017-08-12 00:00:00  
類別資料                train

In [78]:
df2.sort_index(axis=0, ascending=False)

小數  整數         時間   類別資料
3  1.0   3 2017-08-12  train
2  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
0  1.0   3 2017-08-12   test

In [79]:
df2.sort_values(by='類別資料')

小數  整數         時間   類別資料
0  1.0   3 2017-08-12   test
2  1.0   3 2017-08-12   test
1  1.0   3 2017-08-12  train
3  1.0   3 2017-08-12  train

In [80]:
# Pandas 選擇欄、列數據
df1
#欄：只要午餐
#列：只要前三筆

早餐  午餐  晚餐
2017-10-28  85  70  65
2017-10-29  90  65  70
2017-10-30  50  60  90
2017-10-31  85  65  85
2017-11-01  65  80  95
2017-11-02  90  70  85
2017-11-03  95  75  55

In [81]:
df1["晚餐"]

2017-10-28    65
2017-10-29    70
2017-10-30    90
2017-10-31    85
2017-11-01    95
2017-11-02    85
2017-11-03    55
Freq: D, Name: 晚餐, dtype: int32

In [82]:
df1[0:5]

早餐  午餐  晚餐
2017-10-28  85  70  65
2017-10-29  90  65  70
2017-10-30  50  60  90
2017-10-31  85  65  85
2017-11-01  65  80  95

In [83]:
# 欄列一起選
# select by label
print(df1.loc['20171028'])
print(df1.loc[:,['早餐','晚餐']])

早餐    85
午餐    70
晚餐    65
Name: 2017-10-28 00:00:00, dtype: int32
            早餐  晚餐
2017-10-28  85  65
2017-10-29  90  70
2017-10-30  50  90
2017-10-31  85  85
2017-11-01  65  95
2017-11-02  90  85
2017-11-03  95  55


In [84]:
#select by position
print(df1.iloc[3,1])
print(df1.iloc[3:5,1:3])

65
            午餐  晚餐
2017-10-31  65  85
2017-11-01  80  95


In [85]:
#select by ix
print(df1.ix[:3,['午餐','晚餐']])

            午餐  晚餐
2017-10-28  70  65
2017-10-29  65  70
2017-10-30  60  90


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [86]:
# 判斷、篩選
print(df1[df1.午餐>80])

Empty DataFrame
Columns: [早餐, 午餐, 晚餐]
Index: []


In [90]:
df1.iloc[2,2] = 195
df1.loc['20171102','晚餐'] = 60
df1.晚餐[df1.早餐>80] = 40

# nan遺漏直
df1.loc['20171029','午餐'] = np.nan

print(df1)


            早餐    午餐   晚餐
2017-10-28  85  70.0   40
2017-10-29  90   NaN   40
2017-10-30  50  60.0  195
2017-10-31  85  65.0   40
2017-11-01  65  80.0   95
2017-11-02  90  70.0   40
2017-11-03  95  75.0   40


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [88]:
df1

早餐    午餐   晚餐
2017-10-28  85  70.0   40
2017-10-29  90   NaN   40
2017-10-30  50  60.0  195
2017-10-31  85  65.0   40
2017-11-01  65  80.0   95
2017-11-02  90  70.0   40
2017-11-03  95  75.0   40

In [89]:
#完蛋了~~有遺漏值，要怎麼處理?!?!


